name: Call reusable workflow on push to main

on:
  pull_request:
    types: [closed]

jobs:
  call_reusable_workflow:
    uses: Kirti0311/caller_workflow/.github/workflows/action.yaml@main
    with:
      pr_number: ${{ github.event.pull_request.number }}
