name: Call reusable workflow on push to main

on:
    push:
        branches:
            - main

jobs:
    call_reusable_workflow:
        uses: ./.github/workflows/action.yaml
        secrets: inherit